"""aggiunto id_utente a pubblica

Revision ID: 3ffcddb594b2
Revises: 
Create Date: 2026-07-25 13:21:54.905383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffcddb594b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pubblica', sa.Column('id_utente', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'pubblica', 'utenti', ['id_utente'], ['telegram_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pubblica', type_='foreignkey')
    op.drop_column('pubblica', 'id_utente')
    # ### end Alembic commands ###
