"""aggiunto prezzo_storico_id a Pubblica

Revision ID: 782785b0975b
Revises: 3ffcddb594b2
Create Date: 2026-07-25 14:54:54.076894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782785b0975b'
down_revision: Union[str, Sequence[str], None] = '3ffcddb594b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pubblica', sa.Column('prezzo_storico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pubblica', 'prezzi_storico', ['prezzo_storico_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pubblica', type_='foreignkey')
    op.drop_column('pubblica', 'prezzo_storico_id')
    # ### end Alembic commands ###
