"""agginta tabella categoria e collegato prodotti a categoria

Revision ID: ec43fcb3117e
Revises: 502ed186319d
Create Date: 2026-07-27 15:46:05.365553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec43fcb3117e'
down_revision: Union[str, Sequence[str], None] = '502ed186319d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amazon_id', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('id_padre', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_padre'], ['categorie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorie_amazon_id'), 'categorie', ['amazon_id'], unique=True)
    op.add_column('prodotti', sa.Column('categoria_id', sa.BigInteger(), nullable=True))
    op.add_column('prodotti', sa.Column('root_categoria_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'prodotti', 'categorie', ['root_categoria_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'prodotti', 'categorie', ['categoria_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prodotti', type_='foreignkey')
    op.drop_constraint(None, 'prodotti', type_='foreignkey')
    op.drop_column('prodotti', 'root_categoria_id')
    op.drop_column('prodotti', 'categoria_id')
    op.drop_index(op.f('ix_categorie_amazon_id'), table_name='categorie')
    op.drop_table('categorie')
    # ### end Alembic commands ###
